#!/bin/bash

#SBATCH --output=./job_log/slurm-%A.%a.out # stdout file
#SBATCH --error=./job_log/slurm-%A.%a.err  # stderr file

# NOTE please set the following accordingly
#SBATCH --job-name=srt-sft       # create a short name for your job
#SBATCH --nodes=1                # node count
#SBATCH --ntasks=1               # total number of tasks across all nodes
#SBATCH --cpus-per-task=8        # cpu-cores per task (>1 if multi-threaded tasks)
#SBATCH --mem=256G               # memory per cpu-core (4G is default)
#SBATCH --gres=gpu:4             # number of gpus per node
#SBATCH --constraint=gpu80       # only use gpu nodes
#SBATCH --partition=pli-c
#SBATCH --account=arora
#SBATCH --time=0-23:59:00          # total run time limit (HH:MM:SS)

# Phase 1 (SRT) SFT — two stages as described in Section 2.1 of the paper.
#
#   Stage 1 (generation loss, all collected incorrect-init samples):
#       prompt     = x
#       completion = y_init + P_r + y_revised
#
#   Stage 2 (revision loss, ~1k samples), initialized from the stage-1 ckpt:
#       prompt     = x + y_init + P_r
#       completion = y_revised
#
# The two data files are produced by `prepare_data.py`.

export TRANSFORMERS_OFFLINE=1
export HF_HUB_OFFLINE=1
export WANDB_MODE='offline'

set -ex

module purge
module load anaconda3/2024.6
conda activate selfdist

uid="$(date +%Y%m%d_%H%M%S)"
base_model="${BASE_MODEL:-Qwen/Qwen3-4B-Instruct-2507}"
MODEL_NAME=$(basename "$base_model")

# Stage-1 / stage-2 SRT data files (generated by prepare_data.py).
# Defaults follow run_srt_data.sh's "r1_<model>_srt_..." (math) /
# "code_<model>_srt_..." (code) naming, which sft.py's filename substring
# matching expects.
TRAIN_DATA_DIR="${TRAIN_DATA_DIR:-/scratch/gpfs/ARORA/yh0068/Self-Distillation/SD-Zero/self-revision-training/train_data}"
DATA_PREFIX="${DATA_PREFIX:-r1_${MODEL_NAME}_srt}"
stage1_file="${STAGE1_FILE:-${TRAIN_DATA_DIR}/${DATA_PREFIX}_stage1.json}"
stage2_file="${STAGE2_FILE:-${TRAIN_DATA_DIR}/${DATA_PREFIX}_stage2.json}"

lr_stage1=${LR_STAGE1:-5e-6}
lr_stage2=${LR_STAGE2:-5e-6}
epochs_stage1=${EPOCHS_STAGE1:-3}
epochs_stage2=${EPOCHS_STAGE2:-3}
weight_decay=1e-4
micro_batch_size=1
gradient_accumulation_steps=1
gpu_count=$(nvidia-smi -L | wc -l)
push_to_hub=false

echo "Number of GPUs: $gpu_count"

ROOT_PATH="/scratch/gpfs/ARORA/yh0068/Self-Distillation/SD-Zero/self-revision-training/sft"

CKPT_ROOT="${CKPT_ROOT:-$ROOT_PATH/ckpts/${MODEL_NAME}/srt_${uid}}"
stage1_out="${CKPT_ROOT}/stage1"
stage2_out="${CKPT_ROOT}/stage2"
mkdir -p "$stage1_out" "$stage2_out"

run_sft () {
    local model_in=$1
    local train_file=$2
    local epochs=$3
    local lr=$4
    local out_dir=$5

    local master_port=$((20000 + RANDOM % 40000))
    torchrun --nproc-per-node ${gpu_count} --master_port ${master_port} \
        $ROOT_PATH/sft.py \
        --block_size=32768 \
        --per_device_train_batch_size=${micro_batch_size} \
        --per_device_eval_batch_size=${micro_batch_size} \
        --gradient_accumulation_steps=${gradient_accumulation_steps} \
        --num_train_epochs=${epochs} \
        --sample_size=-1 \
        --train_file_path=${train_file} \
        --model_name=${model_in} \
        --warmup_ratio=0.05 \
        --fsdp="full_shard auto_wrap" \
        --fsdp_config="$ROOT_PATH/fsdp_config_qwen.json" \
        --bf16=True \
        --eval_strategy="no" \
        --logging_steps=1 \
        --lr_scheduler_type="cosine" \
        --learning_rate=${lr} \
        --weight_decay=${weight_decay} \
        --adam_beta1=0.9 \
        --adam_beta2=0.95 \
        --output_dir=${out_dir} \
        --push_to_hub=${push_to_hub} \
        --save_steps=1000 \
        --gradient_checkpointing=True \
        --accelerator_config='{"gradient_accumulation_kwargs": {"sync_each_batch": true}}'
}

echo "=== SRT Stage 1: generation loss on $stage1_file ==="
run_sft "$base_model"    "$stage1_file" "$epochs_stage1" "$lr_stage1" "$stage1_out"

echo "=== SRT Stage 2: revision loss on $stage2_file, init from stage 1 ==="
run_sft "$stage1_out"    "$stage2_file" "$epochs_stage2" "$lr_stage2" "$stage2_out"

echo "Done. Stage-1 ckpt: $stage1_out"
echo "      Stage-2 ckpt: $stage2_out  (final SRT model)"
